### ISSUE TITLE
Smart Filter Pro 2.0.3 Filter other fields not working

### ISSUE THREAD

**Issue by riccardo-giardino** [okviz/SmartFilter#11]
Hi, 
I downloaded the Smart Filter Pro 2.0.3 to check capabilities and to compare it with the free version.

I found that the option "Filter other fields" is not working: if you have multiple fields in the filter (eg 4 fields) it looks that only the first one "filters" the other and not in AND all the fields to each-other; the free version in other hands does what I expect.

I attach a simple pbix with the PRO and FREE and the 2 different behaviours

Could you please check it?

Thanks and Regards
Riccardo
[Bug.zip](https://github.com/okviz/SmartFilter/files/2415802/Bug.zip)

**Comment by danieleperilli** [comment]
There is a known bug in the Pro version about that option. We will fix it in the next weeks, we are just waiting a new release of Microsoft API. Anyway, the Pro version uses different code from FREE that is faster and performs better.

**Comment by riccardo-giardino** [comment]
Thanks for the reply,

Do you have any estimated release time?

Regards

**Comment by danieleperilli** [comment]
I just released a new version (2.0.4) that should solve the issue.
