### ISSUE TITLE
Drop down, with tile sizing.

### ISSUE THREAD

**Issue by MrCallahan1** [okviz/SmartFilter#15]
Hey!

First off, I'm a PowerBI rookie, so apologies if this is not an issue, and it's due to my limited knowledge of the tool.

But, from the Report/Dashboard I'm building. I've learned that using Slicers in Dashboards don't seem to work very well (can't pin an individual slicer to dashboard, have to pin whole report to live window). So I wanted to give Smart Filter a shot to see if that'd replace the drop-down functionality I was using with the Slicer.

When using the SmartFilter (free version), it looks like the drop down window is limited to the size of the tile, rather than the drop down being an overlay which can overlap other tiles. See photo links for examples:

[Tile Size 1](https://imgur.com/bK9VGGW)
[Tile Size 2](https://imgur.com/S6LNjMw)
[Slicer](https://imgur.com/DVClpe8)

Trying to keep the tile size as small as possible, but doesn't appear I can do that at the moment.

Is this something that can be accomplished with with SmartFilter? or is this a MS limitation has on add-on developers? Or am I simply doing something wrong? 

Thanks!
Mike

**Comment by marcosqlbi** [comment]
This is a MS limitation for custom visuals - they cannot use the area outside the boundaries of the visual.

**Comment by MrCallahan1** [comment]
Got it, Thanks!
