### ISSUE TITLE
Title on SmartFilter disappears

### ISSUE THREAD

**Issue by AngelaKephart** [okviz/SmartFilter#8]
Hi,  I am working on my Power BI Report on a iPad.  Whenever I use the SmartFilter, the text in the title disappears.  If I move to another tab and move back, the text in the title reappears.  I have the current version 1.1.8.pbiviz.

**Comment by danieleperilli** [comment]
We have no control on the title of the visual. I think it is a bug in Power BI. Please attach here a screencast to explain the issue.

**Comment by AngelaKephart** [comment]
Hi,

SmartFilter on iPad before selection.  Title is clear.



 

After selection

 



 

After clearing selection.

 



 

 

Thanks,

 

Angela

250-714-6807
